### ISSUE TITLE
Mod account manager for WOT has malware

### ISSUE THREAD

**Issue by Willster419** [polarfox-avx/proprietary-stuff#1]
Hello,
Please remove the adware and malware in your mods.
https://puu.sh/ARsVQ/242dc08b60.png

**Comment by polarfox-avx** [comment]
Modification doesnt contains malware or risked adware. If you dont like small ads - please, remove modification.
Also you can create you own version from old source: [https://github.com/spoter/spoter-mods/tree/master/.deprecated/mod_account_manager](url)

**Comment by Willster419** [comment]
"Also you can create you own version from old source:"
-thank you for providing a dead link
"If you don't like small ads - please, remove modification."
-all your mods have been removed. If you remove ads, or allow user consent for ads, let me know, we will consider un-banning you.
